name: Cache Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dummy dependency folder
        run: |
          mkdir -p node_modules
          echo "dummy-package" > node_modules/package.txt

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            node_modules
          key: cache-5f1b75e

      - name: Show cache result
        run: echo "Cache hit/miss: ${{ steps.cache-step.outputs.cache-hit }}"

